# Generated by Django 2.2.3 on 2019-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='target',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
